# Generated by Django 2.0.9 on 2018-12-06 05:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('donate', '0002_auto_20181206_0317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonateinvestPage',
            new_name='GivePage',
        ),
        migrations.RenameModel(
            old_name='DonategivePage',
            new_name='InvestPage',
        ),
        migrations.RenameField(
            model_name='givepage',
            old_name='invest_statement',
            new_name='give_statement',
        ),
        migrations.RenameField(
            model_name='investpage',
            old_name='give_statement',
            new_name='invest_statement',
        ),
    ]
