# Generated by Django 2.0.9 on 2018-11-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='business_name',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
    ]
