# Generated by Django 2.0.9 on 2018-12-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181206_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='missionstatement',
            new_name='mission_statement',
        ),
    ]
